export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const DISPLAY_ERROR = "DISPLAY_ERROR";
export const SET_SECURITY_ERROR = 'SET_SECURITY_ERROR';
export const SET_LOADING_INDICATOR_AUTH = 'SET_LOADING_INDICATOR_AUTH';

export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS'
export const CONFIRM_EMAIL_FAILURE = 'CONFIRM_EMAIL_FAILURE'

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE"

export const SET_PREV_ROUTE ='SET_PREV_ROUTE'


export const TOW_FA_STEP_ONE_SIX_DIGIT = 'TOW_FA_STEP_ONE_SIX_DIGIT';
export const TOW_FA_STEP_ONE_MOBILE_APPLICATION = 'TOW_FA_STEP_ONE_MOBILE_APPLICATION';
export const SET_LOADING_INDICATOR_2FA = 'SET_LOADING_INDICATOR_2FA';
export const SET_CREDENTIALS_2FA = 'SET_CREDENTIALS_2FA';
export const CLEAR_2FA = 'CLEAR_2FA';